adminapp/urls.py
from django.urls import re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.main_view, name='admin'),
    re_path(r'^users/list/$', adminapp.users_list_view, name='users'),
    re_path(r'^user/create/$', adminapp.user_create_view, name='user_create'),
    re_path(r'^user/read/(?P<user_pk>\d+)/$', adminapp.user_detail_view, name='user_detail'),
    re_path(r'^user/update/(?P<user_pk>\d+)/$', adminapp.user_update_view, name='user_update'),
    re_path(r'^user/delete/(?P<user_pk>\d+)/$', adminapp.user_delete_view, name='user_delete'),
    re_path(r'^user/activate/(?P<user_pk>\d+)/$', adminapp.user_activate_view, name='user_activate'),
    re_path(r'^user/changepass/(?P<user_pk>\d+)/$', adminapp.user_change_password, name='user_change_password'),
    # re_path(r'^users/read/$', adminapp.UserListView.as_view(), name='users'),
]

authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    # re_path(r'^login/$', authapp.LoginFormView.as_view(), name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
]

crmapp/urls.py
from django.urls import re_path
import crmapp.views as crmapp

app_name = 'crmapp'

urlpatterns = [

    re_path(r'^$', crmapp.main_crm, name='main_crm'),
    # работники
    re_path(r'^workers/list/$', crmapp.workers_list_view, name='workers_list'),
    re_path(r'^worker/detail/(?P<worker_pk>\d+)/$', crmapp.worker_detail_view, name='worker_detail'),
    re_path(r'^worker/update/(?P<worker_pk>\d+)/$', crmapp.worker_update_view, name='worker_update'),
    # контрагенты
    re_path(r'^partners/$', crmapp.partners_view, name='partners'),
    re_path(r'^partner/create/$', crmapp.partner_create_view, name='partner_create'),
    re_path(r'^partner/read/(?P<partner_pk>\d+)/$', crmapp.partner_read_view, name='partner_read'),
    re_path(r'^partner/update/(?P<partner_pk>\d+)/$', crmapp.partner_update_view, name='partner_update'),
    # фирмы
    re_path(r'^firms/$', crmapp.firms_view, name='firms'),
    re_path(r'^firm/create/$', crmapp.firm_create_view, name='firm_create'),
    re_path(r'^firm/read/(?P<firm_pk>\d+)/$', crmapp.firm_read_view, name='firm_read'),
    re_path(r'^firm/update/(?P<firm_pk>\d+)/$', crmapp.firm_update_view, name='firm_update'),
    # работы/услуги
    re_path(r'^services/$', crmapp.services_view, name='services'),
    re_path(r'^service/create/$', crmapp.service_create_view, name='service_create'),
    re_path(r'^service/update/(?P<service_pk>\d+)/$', crmapp.service_update_view, name='service_update'),
    # договора
    re_path(r'^contracts/$', crmapp.contracts_view, name='contracts'),
    re_path(r'^contract/create/$', crmapp.contract_create_view, name='contract_create'),
    re_path(r'^contract/read/(?P<contract_pk>\d+)/$', crmapp.contract_read_view, name='contract_read'),
    re_path(r'^contract/update/(?P<contract_pk>\d+)/$', crmapp.contract_update_view, name='contract_update'),
    re_path(r'^contract/edit/$', crmapp.contract_edit_view),
    # счета
    re_path(r'^invoices/$', crmapp.invoices_view, name='invoices'),
    re_path(r'^invoice/create/(?P<contract_pk>\d+)$', crmapp.invoice_create_view, name='invoice_create'),
    re_path(r'^invoice/read/(?P<invoice_pk>\d+)$', crmapp.invoice_read_view, name='invoice_read'),
    re_path(r'^invoice/update/(?P<invoice_pk>\d+)$', crmapp.invoice_update_view, name='invoice_update'),
    re_path(r'^invoice/edit/$', crmapp.invoice_edit_view),
    # акты
    re_path(r'^acts/$', crmapp.acts_view, name='acts'),
    re_path(r'^act/create/(?P<contract_pk>\d+)/$', crmapp.act_create_view, name='act_create'),
    re_path(r'^act/read/(?P<act_pk>\d+)/$', crmapp.act_read_view, name='act_read'),
    re_path(r'^act/update/(?P<act_pk>\d+)/$', crmapp.act_update_view, name='act_update'),
    # проекты
    re_path(r'^projects/$', crmapp.projects_view, name='projects'),
    re_path(r'^project/create/(?P<contract_pk>\d+)$', crmapp.project_create_view, name='project_create'),
    # re_path(r'^project/read/(?P<project_pk>\d+)$', crmapp.project_read_view, name='project_read'),
    re_path(r'^project/update/(?P<project_pk>\d+)$', crmapp.project_update_view, name='project_update'),
    # задачи
    # re_path(r'^tasks/$', crmapp.tasks_view, name='tasks'),
    re_path(r'^task/create/(?P<project_pk>\d+)$', crmapp.task_create_view, name='task_create'),
    # re_path(r'^task/read/(?P<project_pk>\d+)$', crmapp.project_read_view, name='project_read'),
    re_path(r'^task/update/(?P<task_pk>\d+)$', crmapp.task_update_view, name='task_update'),
]

mainapp/urls.py
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^tasks/all/$', mainapp.all_task_view, name='all_tasks'),
    re_path(r'^tasks/done/$', mainapp.task_done_view, name='tasks_done'),
    re_path(r'^task/edit/(?P<task_pk>\d+)$', mainapp.task_edit_view, name='task_edit'),
    # re_path(r'^voice/$', mainapp.voicep243, name='voicep243'),
    # re_path(r'^logout/$', authapp.logout, name='logout'),
]

vepp/urls.py
# from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, include

import mainapp.views as mainapp
# import adminapp.views as adminapp

urlpatterns = [
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^main/', include('mainapp.urls', namespace='main')),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    re_path(r'^crm/', include('crmapp.urls', namespace='crm')),
    # re_path(r'^admin/', adminapp.main_view, name='admin'),
    # re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, HttpResponseRedirect, reverse

from crmapp.models import Task, Project
from crmapp.forms import TaskEditForm


@login_required
def main(request):
    title = 'Завдання'
    user = request.user
    projects = Project.objects.filter(is_finished=False)
    tasks = Task.objects.filter(worker=user).exclude(status='done')

    context = {
        'title': title,
        'task_list': tasks,
        'project_list': projects,
    }
    return render(request, 'mainapp/index.html', context)


@login_required
def all_task_view(request):
    title = 'Всі завдання'
    projects = Project.objects.all()
    all_tasks = Task.objects.filter(worker=request.user)

    context = {
        'title': title,
        'project_list': projects,
        'task_list': all_tasks,
    }
    return render(request, 'mainapp/index.html', context)


@login_required
def task_done_view(request):
    title = 'Завершені завдання'
    projects = Project.objects.all()
    all_tasks = Task.objects.filter(worker=request.user, status='done')

    context = {
        'title': title,
        'project_list': projects,
        'task_list': all_tasks,
    }
    return render(request, 'mainapp/index.html', context)


@login_required
def task_edit_view(request, task_pk):
    title = 'Редагувати завдання'
    task = get_object_or_404(Task, pk=task_pk)
    if request.method == 'POST':
        form = TaskEditForm(request.POST, instance=task)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('main'))
            except Exception as e:
                pass
    else:
        form = TaskEditForm(instance=task)

    context = {
        'title': title,
        'form': form,
        'object': task,
    }
    return render(request, 'mainapp/task_edit.html', context)

mainapp/templates/mainapp/includes/inc_left_menu.html
{% load staticfiles %}

<ul class="nav nav-pills nav-stacked custom-nav">

    <!-- админ -->
    {% if user.is_superuser %}
    <li class="menu-list {% if request.resolver_match.namespace == 'admin' %} nav-active {% endif %}">
        <a href="{% url 'admin:admin' %}"><i class="fa fa-cogs"></i> <span>Адміністрування</span></a>
        <ul class="sub-menu-list">
            <li class="{% if request.resolver_match.url_name == 'admin' %} active {% endif %}">
                <a href="{% url 'admin:admin' %}"> Адмінпанель</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'users' %} active {% endif %}">
                <a href="{% url 'admin:users' %}"> Користувачі</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'user_create' %} active {% endif %}">
                <a href="{% url 'admin:user_create' %}"> Новий користувач</a>
            </li>
        </ul>
    </li>
    {% endif %}

    <!-- директор/помошник -->
    {% if user.is_dir or user.is_assistant or user.is_superuser %}
    <li class="menu-list {% if request.resolver_match.namespace == 'crm' %} nav-active {% endif %}">
        <a href="{% url 'crm:main_crm' %}"><i class="fa fa-desktop"></i> <span>CRM</span></a>
        <ul class="sub-menu-list">
            <li class="{% if request.resolver_match.url_name == 'main_crm' %} active {% endif %}">
                <a href="{% url 'crm:main_crm' %}"> Головна</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'partners' or request.resolver_match.url_name == 'partner_read' or request.resolver_match.url_name == 'partner_update' %} active {% endif %}">
                <a href="{% url 'crm:partners' %}"> Контрагенти</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'contracts' or request.resolver_match.url_name == 'contract_read'  or request.resolver_match.url_name == 'contract_update' %} active {% endif %}">
                <a href="{% url 'crm:contracts' %}"> Договора</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'invoices' or request.resolver_match.url_name == 'invoice_update' or request.resolver_match.url_name == 'invoice_read' %} active {% endif %}">
                <a href="{% url 'crm:invoices' %}"> Рахунки</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'acts' or request.resolver_match.url_name == 'act_update' or request.resolver_match.url_name == 'act_read' %} active {% endif %}">
                <a href="{% url 'crm:acts' %}"> Акти</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'firms' or request.resolver_match.url_name == 'firm_create' or request.resolver_match.url_name == 'firm_update' or request.resolver_match.url_name == 'firm_read' %} active {% endif %}">
                <a href="{% url 'crm:firms' %}"> Фірми</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'projects' or request.resolver_match.url_name == 'project_create' or request.resolver_match.url_name == 'project_update' or request.resolver_match.url_name == 'project_read' %} active {% endif %}">
                <a href="{% url 'crm:projects' %}"> Проекти</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'services' %} active {% endif %}">
                <a href="{% url 'crm:services' %}"> Послуги</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'workers_list' or request.resolver_match.url_name == 'worker_detail' or request.resolver_match.url_name == 'worker_update' %} active {% endif %}">
                <a href="{% url 'crm:workers_list' %}"> Працівники</a>
            </li>
        </ul>
    </li>
    {% endif %}

    <!-- задачи -->
    {% if user.is_authenticated %}
    <li class="menu-list {% if request.resolver_match.namespace == 'main' or request.resolver_match.url_name == 'main' %} nav-active {% endif %}">
        <a href="{#% url 'admin:admin' %#}"><i class="fa fa-book"></i> <span>Завдання</span></a>
        <ul class="sub-menu-list">
            <li class="{% if request.resolver_match.url_name == 'all_tasks' %} active {% endif %}">
                <a href="{% url 'main:all_tasks' %}"> Всі</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'main' %} active {% endif %}">
                <a href="{% url 'main' %}"> Призначені</a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'tasks_done' %} active {% endif %}">
                <a href="{% url 'main:tasks_done' %}"> Завершені</a>
            </li>
        </ul>
    </li>
    {% endif %}
</ul>
<!--{{ request.resolver_match.url_name}}-->
<!--{{user}} {{object.username}}-->

mainapp/templates/mainapp/includes/inc_quick_button.html
{% load staticfiles %}

<ul class="notification-menu" style="margin: 0;">
    <li>
        <a class="btn btn-default dropdown-toggle info-number" type="button" href="{% url 'crm:partners' %}">
            <i class="fa fa-users fa-lg"></i>
        </a>
    </li>
    <li>
        <a class="btn btn-default dropdown-toggle info-number" type="button" href="{% url 'crm:contracts' %}">
            <i class="fa fa-briefcase fa-lg"></i>
        </a>
    </li>
</ul>

mainapp/templates/mainapp/includes/inc_right_menu.html
{% load staticfiles %}
{% load tags %}

<ul class="notification-menu">
    <!--<li>-->
        <!--<a class="btn btn-default dropdown-toggle info-number" href="#">-->
            <!--<i class="fa fa-tasks"></i>-->
            <!--<span class="badge">{% if count_task != 0 %}{{ count_task }}{% endif %}</span>-->
            <!--{{ user.task.all.count }}-->
        <!--</a>-->
    <!--</li>-->
    <li>
        <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <img src="{#% static '/images/photos/user-avatar.png' %#}" alt=""/>
            <img src="{{ user.avatar|default_avatar }}" alt=""/>
            {{ user.first_name }}
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu dropdown-menu-usermenu pull-right">
            <!--<li><a href="#"><i class="fa fa-file-o"></i> Завдання</a></li>-->
            <li><a href="{% url 'crm:worker_update' user.pk %}"><i class="fa fa-user"></i> Профіль</a></li>
            <li><a href="{% url 'auth:logout' %}"><i class="fa fa-sign-out"></i> Вихід</a></li>
        </ul>
    </li>
</ul>