adminapp/urls.py
from django.urls import re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.main_view, name='admin'),
    re_path(r'^users/list/$', adminapp.users_list_view, name='users'),
    re_path(r'^user/create/$', adminapp.user_create_view, name='user_create'),
    re_path(r'^user/read/(?P<user_pk>\d+)/$', adminapp.user_detail_view, name='user_detail'),
    re_path(r'^user/update/(?P<user_pk>\d+)/$', adminapp.user_update_view, name='user_update'),
    re_path(r'^user/delete/(?P<user_pk>\d+)/$', adminapp.user_delete_view, name='user_delete'),
    re_path(r'^user/activate/(?P<user_pk>\d+)/$', adminapp.user_activate_view, name='user_activate'),
    re_path(r'^user/changepass/(?P<user_pk>\d+)/$', adminapp.user_change_password, name='user_change_password'),
    # re_path(r'^users/read/$', adminapp.UserListView.as_view(), name='users'),
]

vepp/urls.py
# from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, include

import mainapp.views as mainapp
# import adminapp.views as adminapp

urlpatterns = [
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^main/', include('mainapp.urls', namespace='main')),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    re_path(r'^crm/', include('crmapp.urls', namespace='crm')),
    # re_path(r'^admin/', adminapp.main_view, name='admin'),
    # re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
# from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test, login_required
# from django.views.generic.list import ListView

from authapp.models import ProjectUser
from crmapp.models import Task
from authapp.forms import UserRegisterForm, UserAdminUpdateForm, UserPassChangeForm


# админка
@user_passes_test(lambda user: user.is_superuser)
def main_view(request):
    title = 'Адміністрування'
    count = ProjectUser.objects.all().count()
    # count_tasks = request.user.task.exclude(status='done').count()
    tasks, count_tasks = Task.get_task(request.user)

    context = {
        'title': title,
        'object': count,
        'task_list': tasks,
        'count_task': count_tasks,
    }
    return render(request, 'adminapp/index.html', context)


# просмотр списка зарегестрированных пользователей
@user_passes_test(lambda user: user.is_superuser)
def users_list_view(request):
    title = 'Користувачі'
    users_list = ProjectUser.objects.all().order_by('-is_active', 'username')

    context = {
        'title': title,
        'object_list': users_list,
    }
    return render(request, 'adminapp/users_list.html', context)


# создание пользователя
@user_passes_test(lambda user: user.is_superuser)
def user_create_view(request):
    title = 'Новий користувач'
    form = UserRegisterForm()
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('admin:users'))
            except ValueError:
                pass

    context = {
        'title': title,
        'form': form,
    }
    return render(request, 'adminapp/user_create.html', context)


# просмотр детальной информации о пользователе
@user_passes_test(lambda user: user.is_superuser)
def user_detail_view(request, user_pk):
    title = 'Профіль користувача'
    user = get_object_or_404(ProjectUser, pk=user_pk)

    context = {
        'title': title,
        'object': user,
    }
    return render(request, 'adminapp/user_detail.html', context)


# редактирование профиля пользователя
@user_passes_test(lambda user: user.is_superuser)
def user_update_view(request, user_pk):
    title = 'Редагувати профіль'
    user = get_object_or_404(ProjectUser, pk=user_pk)
    if user:
        if request.method == 'POST':
            form = UserAdminUpdateForm(request.POST, request.FILES, instance=user)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:users'))
        else:
            form = UserAdminUpdateForm(instance=user)

        context = {
            'title': title,
            'form': form,
            'object': user,
        }
        return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda user: user.is_superuser)
def user_delete_view(request, user_pk):
    user = get_object_or_404(ProjectUser, pk=int(user_pk))
    if user:
        user.is_active = False
        user.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@user_passes_test(lambda user: user.is_superuser)
def user_activate_view(request, user_pk):
    user = get_object_or_404(ProjectUser, pk=user_pk)
    if user:
        user.is_active = True
        user.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@user_passes_test(lambda user: user.is_superuser)
def user_change_password(request, user_pk):
    title = 'Зміна пароля користувача'
    user = get_object_or_404(ProjectUser, pk=user_pk)
    if user:
        if request.method == 'POST':
            form = UserPassChangeForm(user, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:users'))
        else:
            form = UserPassChangeForm(user)

        context = {
            'title': title,
            'form': form,
            'object': user,
        }

        return render(request, 'adminapp/user_change_password.html', context)
# class UserListView(ListView):
#     model = ProjectUser
#     template_name = 'adminapp/users_list.html'
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['title'] = 'Користувачі'
#         return context
#
#     @method_decorator(user_passes_test(lambda user: user.is_superuser))
#     def dispatch(self, request, *args, **kwargs):
#         return super().dispatch(request, *args, **kwargs)

adminapp/templates/adminapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} / {{ title }}
{% endblock %}

<!--{% block breadcrumbs %}-->

    <!--<ul class="breadcrumb">-->
        <!--<li>-->
            <!--{{ block.super }}-->
        <!--</li>-->
        <!--<li><a href="{% url 'admin:admin' %}">Адміністрування</a></li>-->
    <!--</ul>-->
<!--{% endblock %}-->

{% block container %}
<div class="wrapper widgets">
    <div class="row">
        <div class="row states-info">
            <a href="{% url 'admin:users' %}">
                <div class="col-md-3">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-4">
                                    <i class="fa fa-users"></i>
                                </div>
                                <div class="col-xs-8">
                                    <h4>Користувачі - {{ object }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <a href="{% url 'admin:user_create' %}">
                <div class="col-md-3">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-4">
                                    <i class="fa fa-user-plus"></i>
                                </div>
                                <div class="col-xs-8">
                                    <h4>Новий користувач</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/user_change_password.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
    {{ block.super }} / {{ title }}
{% endblock %}

<!--{% block breadcrumbs %}-->

    <!--<ul class="breadcrumb">-->
        <!--<li>-->
            <!--{{ block.super }}-->
        <!--</li>-->
        <!--<li><a href="{% url 'admin:user_update' object.pk%}">{{ object.last_name }} {{ object.first_name }}</a></li>-->
    <!--</ul>-->
<!--{% endblock %}-->

{% block container %}
<div class="row">
    <div class="col-lg-8">
        <section class="panel">
            <header class="panel-heading">{{ title }}</header>
            <div class="panel-body">
                <div class="form">
                    <form id="signupForm" class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary" type="submit">
                            Зберегти
                        </button>
                        <a href="{% url 'admin:users' %}">
                            <button class="btn btn-default" type="button">
                                Відмінити
                            </button>
                        </a>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/user_create.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} / {{ title }}
{% endblock %}

<!--{% block breadcrumbs %}-->

    <!--<ul class="breadcrumb">-->
        <!--<li>-->
            <!--{{ block.super }}-->
        <!--</li>-->
        <!--<li><a href="{% url 'admin:user_create' %}">{{ title }}</a></li>-->
    <!--</ul>-->
<!--{% endblock %}-->

{% block container %}
<div class="row">
    <div class="col-lg-8">
        <section class="panel">
            <header class="panel-heading">{{ title }}</header>
            <div class="panel-body">
                <div class="form">
                    <form id="signupForm" class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!--{{ form.as_p }}-->
                        {% for field in form %}
                        <div class="form-group">
                            <label class="control-label col-lg-2">{{ field.label_tag }}</label>
                            <div class="col-lg-10">
                                {{ field }}
                            </div>
                        </div>
                        {% endfor %}
                        <button class="btn btn-primary" type="submit">
                            Зберегти
                        </button>
                        <a href="{% url 'admin:admin' %}">
                            <button class="btn btn-default" type="button">
                                Відмінити
                            </button>
                        </a>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/user_detail.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
    {{ block.super }} / {{ title }}
{% endblock %}

<!--{% block breadcrumbs %}-->
    <!--<ul class="breadcrumb">-->
        <!--<li>-->
            <!--{{ block.super }}-->
        <!--</li>-->
        <!--<li><a href="{% url 'admin:user_detail' object.pk %}">{{ object.last_name }} {{ object.first_name }}</a></li>-->
    <!--</ul>-->
<!--{% endblock %}-->

{% block container %}
<div class="row">
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-body">
                        <div class="profile-pic text-center">
                            <img src="{{ object.avatar|default_avatar }}" style="max-width: 200px; max-height: 200px;"
                                 alt="">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                    <div class="panel">
                        <div class="panel-body">
                            <ul class="p-info">
                                <li>
                                    <div class="title">Ім'я</div>
                                    <div class="desk">{{ object.first_name }}</div>
                                </li>
                                <li>
                                    <div class="title">Тип профілю</div>
                                    <div class="desk">
                                        {% if object.is_superuser %}Адміністратор
                                        {% elif object.is_dir %}Керівник
                                        {% elif object.is_assistant %}Помічник
                                        {% else %}Працівник
                                        {% endif %}
                                    </div>
                                </li>
                                <li>
                                    <div class="title">Логін</div>
                                    <div class="desk">{{ object.username }}</div>
                                </li>
                                <li>
                                    <div class="title">Дата реєстрації</div>
                                    <div class="desk">{{ object.date_joined }}</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-8">
                <div class="panel">
                    <div class="panel-body">
                        <ul class="p-info">
                            <li>
                                <div class="title">Прізвище</div>
                                <div class="desk">{{ object.last_name }}</div>
                            </li>
                            <li>
                                <div class="title">Ім'я</div>
                                <div class="desk">{{ object.first_name }}</div>
                            </li>
                            <li>
                                <div class="title">По-батькові</div>
                                <div class="desk">{{ object.parent_name }}</div>
                            </li>
                            <li>
                                <div class="title">e-mail</div>
                                <div class="desk">{{ object.email }}</div>
                            </li>
                            <li>
                                <div class="title">Телефон</div>
                                <div class="desk">{{ object.phone1 }}<br>
                                {% if object.phone2 == None %} &nbsp;{% endif %}</div>
                            </li>
                            <li>
                                <div class="title">Дата народження</div>
                                <div class="desk">{{ object.date_of_birth }}</div>
                            </li>
                            <li>
                                <div class="title">Обліковий запис</div>
                                <div class="desk">
                                    {% if object.is_active == True %}
                                        Включений
                                    {% else %}
                                        <span style="color: red;">Відключений</span>
                                    {% endif %}
                                </div>
                            </li>
                            <li>
                                <div class="title">Останній вхід в систему</div>
                                <div class="desk">
                                    {% if object.last_login == None %}
                                    жодного разу
                                    {% else %}
                                    {{ object.last_login }}
                                    {% endif %}
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
    {{ block.super }} / {{ title }}
{% endblock %}

<!--{% block breadcrumbs %}-->

    <!--<ul class="breadcrumb">-->
        <!--<li>-->
            <!--{{ block.super }}-->
        <!--</li>-->
        <!--<li><a href="{% url 'admin:user_update' object.pk%}">{{ object.last_name }} {{ object.first_name }}</a></li>-->
    <!--</ul>-->
<!--{% endblock %}-->

{% block container %}
<div class="row">
    <div class="col-lg-8">
        <section class="panel">
            <header class="panel-heading">{{ title }}</header>
            <div class="panel-body">
                <div class="form">
                    <form id="signupForm" class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-lg-2">{{ form.username.label_tag }}</label>
                            <div class="col-lg-10">
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">{{ form.first_name.label_tag }}</label>
                            <div class="col-lg-10">
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">{{ form.last_name.label_tag }}</label>
                            <div class="col-lg-10">
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">{{ form.parent_name.label_tag }}</label>
                            <div class="col-lg-10">
                                {{ form.parent_name }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">{{ form.email.label_tag }}</label>
                            <div class="col-lg-10">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">{{ form.phone1.label_tag }}</label>
                            <div class="col-lg-10">
                                {{ form.phone1 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">{{ form.phone2.label_tag }}</label>
                            <div class="col-lg-10">
                                {{ form.phone2 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">{{ form.date_of_birth.label_tag }}</label>
                            <div class="col-md-4 col-xs-11">
                                <div data-date-viewmode="years" data-date-format="dd.mm.yyyy" data-date="12-02-2012"
                                     class="input-append date dpYears">
                                    {{ form.date_of_birth }}
                                    <span class="input-group-btn add-on">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fa fa-calendar"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>
                        {% if user.is_superuser %}
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">{{ form.is_active.label_tag }}</label>
                                <div class="col-sm-9 icheck">
                                    <div class="flat-green single-row">
                                        <div class="radio">
                                            {{ form.is_active }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">{{ form.is_dir.label_tag }}</label>
                                <div class="col-sm-9 icheck">
                                    <div class="flat-green single-row">
                                        <div class="radio">
                                            {{ form.is_dir }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">{{ form.is_assistant.label_tag }}</label>
                                <div class="col-sm-9 icheck">
                                    <div class="flat-green single-row">
                                        <div class="radio">
                                            {{ form.is_assistant }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">{{ form.is_client.label_tag }}</label>
                                <div class="col-sm-9 icheck">
                                    <div class="flat-green single-row">
                                        <div class="radio">
                                            {{ form.is_client }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        <div class="form-group last">
                            <label class="control-label col-lg-2">{{ form.avatar.label_tag }}</label>
                            <div class="col-md-9">
                                <div class="fileupload fileupload-new" data-provides="fileupload">
                                    <div class="fileupload-preview fileupload-new thumbnail"
                                         style="max-width: 200px; max-height: 200px;">
                                        <img src="{{ object.avatar|default_avatar }}"
                                             style="max-width: 200px; max-height: 150px;" alt="">
                                    </div>
                                    <div>
                                        {{ form.avatar }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 col-xs-11">
                                {{ form.password }}
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">
                            Зберегти
                        </button>
                        <a href="{% url 'admin:users' %}">
                            <button class="btn btn-default" type="button">
                                Відмінити
                            </button>
                        </a>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/users_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
    {{ block.super }} / {{ title }}
{% endblock %}

<!--{% block breadcrumbs %}-->

    <!--<ul class="breadcrumb">-->
        <!--<li>-->
            <!--{{ block.super }}-->
        <!--</li>-->
        <!--<li><a href="{% url 'admin:users' %}">{{ title }}</a></li>-->
    <!--</ul>-->
<!--{% endblock %}-->

{% block container %}
<div class="directory-info-row">
    <div class="row">
        {% for object in object_list %}
        <div class="col-lg-4 col-sm-6">
            <div class="panel">
                <div class="panel-body" style="{% if not object.is_active %}opacity: 0.3{% endif %}">
                    <h4>{{ object.last_name }} {{ object.first_name }}</h4>
                    <div class="media">
                        <a class="pull-left" href="{% url 'admin:user_detail' object.pk %}">
                            <img class="thumb media-object" src="{{ object.avatar|default_avatar }}"
                                 style="max-width: 100px; max-height: 100px;" alt="">
                        </a>
                        <div class="media-body">
                            <address>
                                <strong>
                                    {% if object.is_superuser %}Адміністратор
                                    {% elif object.is_dir %}Керівник
                                    {% elif object.is_assistant %}Помічник
                                    {% else %}Працівник
                                    {% endif %}
                                </strong><br>
                                Реєстрація:<br> {{ object.date_joined }}<br>
                                <i class="fa fa-calendar" title="дата народження"></i> : {{ object.date_of_birth }}<br>
                                <i class="fa fa-phone fa-lg"></i> : {{ object.phone1 }}
                            </address>
                            <ul class="nav nav-pills p-option">
                                {% if not object.is_superuser %}
                                <li>
                                    <a href="{% url 'admin:user_update' object.pk %}">
                                        <i class="fa fa-pencil" aria-hidden="true" title="Редагувати"></i>
                                    </a>
                                </li>
                                {% endif %}
                                <li>
                                    <a href="{% url 'admin:user_detail' object.pk %}">
                                        <i class="fa fa-eye" aria-hidden="true" title="Переглянути"></i>
                                    </a>
                                </li>
                                {% if user.is_superuser %}
                                <li>
                                    {% if not object.is_superuser %}
                                    <a href="{% url 'admin:user_change_password' object.pk %}">
                                        <i class="fa fa-key" aria-hidden="true" title="Змінити пароль"></i>
                                    </a>
                                    {% endif %}
                                </li>
                                <li>
                                    {% if not object.is_superuser %}
                                        {% if object.is_active %}
                                            <a href="{% url 'admin:user_delete' object.pk %}">
                                                <i class="fa fa-lock" aria-hidden="true" title="Заблокувати"></i>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'admin:user_activate' object.pk %}">
                                                <i class="fa fa-unlock" aria-hidden="true" title="Разблокувати"></i>
                                            </a>
                                        {% endif %}
                                    {% endif %}
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}