adminapp/urls.py
from django.urls import re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.main_view, name='admin'),
    re_path(r'^users/list/$', adminapp.users_list_view, name='users'),
    re_path(r'^user/create/$', adminapp.user_create_view, name='user_create'),
    re_path(r'^user/read/(?P<user_pk>\d+)/$', adminapp.user_detail_view, name='user_detail'),
    re_path(r'^user/update/(?P<user_pk>\d+)/$', adminapp.user_update_view, name='user_update'),
    re_path(r'^user/delete/(?P<user_pk>\d+)/$', adminapp.user_delete_view, name='user_delete'),
    re_path(r'^user/activate/(?P<user_pk>\d+)/$', adminapp.user_activate_view, name='user_activate'),
    re_path(r'^user/changepass/(?P<user_pk>\d+)/$', adminapp.user_change_password, name='user_change_password'),
    # re_path(r'^users/read/$', adminapp.UserListView.as_view(), name='users'),
]

authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    # re_path(r'^login/$', authapp.LoginFormView.as_view(), name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
]

crmapp/urls.py
from django.urls import re_path
import crmapp.views as crmapp

app_name = 'crmapp'

urlpatterns = [

    re_path(r'^$', crmapp.main_crm, name='main_crm'),
    # работники
    re_path(r'^workers/list/$', crmapp.workers_list_view, name='workers_list'),
    re_path(r'^worker/detail/(?P<worker_pk>\d+)/$', crmapp.worker_detail_view, name='worker_detail'),
    re_path(r'^worker/update/(?P<worker_pk>\d+)/$', crmapp.worker_update_view, name='worker_update'),
    # контрагенты
    re_path(r'^partners/$', crmapp.partners_view, name='partners'),
    re_path(r'^partner/create/$', crmapp.partner_create_view, name='partner_create'),
    re_path(r'^partner/read/(?P<partner_pk>\d+)/$', crmapp.partner_read_view, name='partner_read'),
    re_path(r'^partner/update/(?P<partner_pk>\d+)/$', crmapp.partner_update_view, name='partner_update'),
    # фирмы
    re_path(r'^firms/$', crmapp.firms_view, name='firms'),
    re_path(r'^firm/create/$', crmapp.firm_create_view, name='firm_create'),
    re_path(r'^firm/read/(?P<firm_pk>\d+)/$', crmapp.firm_read_view, name='firm_read'),
    re_path(r'^firm/update/(?P<firm_pk>\d+)/$', crmapp.firm_update_view, name='firm_update'),
    # работы/услуги
    re_path(r'^services/$', crmapp.services_view, name='services'),
    re_path(r'^service/create/$', crmapp.service_create_view, name='service_create'),
    re_path(r'^service/update/(?P<service_pk>\d+)/$', crmapp.service_update_view, name='service_update'),
    # договора
    re_path(r'^contracts/$', crmapp.contracts_view, name='contracts'),
    re_path(r'^contract/create/$', crmapp.contract_create_view, name='contract_create'),
    re_path(r'^contract/read/(?P<contract_pk>\d+)/$', crmapp.contract_read_view, name='contract_read'),
    re_path(r'^contract/update/(?P<contract_pk>\d+)/$', crmapp.contract_update_view, name='contract_update'),
    re_path(r'^contract/edit/$', crmapp.contract_edit_view),
    # счета
    re_path(r'^invoices/$', crmapp.invoices_view, name='invoices'),
    re_path(r'^invoice/create/(?P<contract_pk>\d+)$', crmapp.invoice_create_view, name='invoice_create'),
    re_path(r'^invoice/read/(?P<invoice_pk>\d+)$', crmapp.invoice_read_view, name='invoice_read'),
    re_path(r'^invoice/update/(?P<invoice_pk>\d+)$', crmapp.invoice_update_view, name='invoice_update'),
    re_path(r'^invoice/edit/$', crmapp.invoice_edit_view),
    # акты
    re_path(r'^acts/$', crmapp.acts_view, name='acts'),
    re_path(r'^act/create/(?P<contract_pk>\d+)/$', crmapp.act_create_view, name='act_create'),
    re_path(r'^act/read/(?P<act_pk>\d+)/$', crmapp.act_read_view, name='act_read'),
    re_path(r'^act/update/(?P<act_pk>\d+)/$', crmapp.act_update_view, name='act_update'),
    # проекты
    re_path(r'^projects/$', crmapp.projects_view, name='projects'),
    re_path(r'^project/create/(?P<contract_pk>\d+)$', crmapp.project_create_view, name='project_create'),
    # re_path(r'^project/read/(?P<project_pk>\d+)$', crmapp.project_read_view, name='project_read'),
    re_path(r'^project/update/(?P<project_pk>\d+)$', crmapp.project_update_view, name='project_update'),
    # задачи
    # re_path(r'^tasks/$', crmapp.tasks_view, name='tasks'),
    re_path(r'^task/create/(?P<project_pk>\d+)$', crmapp.task_create_view, name='task_create'),
    # re_path(r'^task/read/(?P<project_pk>\d+)$', crmapp.project_read_view, name='project_read'),
    re_path(r'^task/update/(?P<task_pk>\d+)$', crmapp.task_update_view, name='task_update'),
]

mainapp/urls.py
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^tasks/all/$', mainapp.all_task_view, name='all_tasks'),
    re_path(r'^tasks/done/$', mainapp.task_done_view, name='tasks_done'),
    re_path(r'^task/edit/(?P<task_pk>\d+)$', mainapp.task_edit_view, name='task_edit'),
    # re_path(r'^voice/$', mainapp.voicep243, name='voicep243'),
    # re_path(r'^logout/$', authapp.logout, name='logout'),
]

vepp/urls.py
# from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, include

import mainapp.views as mainapp
# import adminapp.views as adminapp

urlpatterns = [
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^main/', include('mainapp.urls', namespace='main')),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    re_path(r'^crm/', include('crmapp.urls', namespace='crm')),
    # re_path(r'^admin/', adminapp.main_view, name='admin'),
    # re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, HttpResponseRedirect, reverse

from crmapp.models import Task, Project
from crmapp.forms import TaskEditForm


@login_required
def main(request):
    title = 'Завдання'
    user = request.user
    projects = Project.objects.filter(is_finished=False)
    tasks = Task.objects.filter(worker=user).exclude(status='done')

    context = {
        'title': title,
        'task_list': tasks,
        'project_list': projects,
    }
    return render(request, 'mainapp/index.html', context)


@login_required
def all_task_view(request):
    title = 'Всі завдання'
    projects = Project.objects.all()
    all_tasks = Task.objects.filter(worker=request.user)

    context = {
        'title': title,
        'project_list': projects,
        'task_list': all_tasks,
    }
    return render(request, 'mainapp/index.html', context)


@login_required
def task_done_view(request):
    title = 'Завершені завдання'
    projects = Project.objects.all()
    all_tasks = Task.objects.filter(worker=request.user, status='done')

    context = {
        'title': title,
        'project_list': projects,
        'task_list': all_tasks,
    }
    return render(request, 'mainapp/index.html', context)


@login_required
def task_edit_view(request, task_pk):
    title = 'Редагувати завдання'
    task = get_object_or_404(Task, pk=task_pk)
    if request.method == 'POST':
        form = TaskEditForm(request.POST, instance=task)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('main'))
            except Exception as e:
                pass
    else:
        form = TaskEditForm(instance=task)

    context = {
        'title': title,
        'form': form,
        'object': task,
    }
    return render(request, 'mainapp/task_edit.html', context)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load tags %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <link rel="shortcut icon" href="#" type="image/png">

    <title>
        {% block title %}
        Вепп
        {% endblock %}
    </title>

    {% block css %}
    <!--pickers css-->
    <link rel="stylesheet" type="text/css" href="{% static '/js/bootstrap-datepicker/css/datepicker-custom.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/js/bootstrap-timepicker/css/timepicker.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/js/bootstrap-colorpicker/css/colorpicker.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/js/bootstrap-daterangepicker/daterangepicker-bs3.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static '/js/bootstrap-datetimepicker/css/datetimepicker-custom.css' %}"/>

    <!--icheck-->
    <link href="{% static '/js/iCheck/skins/minimal/minimal.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/minimal/red.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/minimal/green.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/minimal/blue.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/minimal/yellow.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/minimal/purple.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/square/square.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/square/red.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/square/blue.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/square/green.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/square/yellow.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/square/purple.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/flat/grey.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/flat/red.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/flat/green.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/flat/blue.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/flat/yellow.css' %}" rel="stylesheet">
    <link href="{% static '/js/iCheck/skins/flat/purple.css' %}" rel="stylesheet">

    <!--dashboard calendar-->
    <link href="{% static '/css/clndr.css' %}" rel="stylesheet">


    <!--common-->
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
    <link href="{% static '/css/style-responsive.css' %}" rel="stylesheet">

    <link href="{% static '/css/table-div.css' %}" rel="stylesheet">
    {% endblock %}

</head>

<body class="sticky-header left-side-collapsed">

<section>

    <!-- left side start-->
    <div class="left-side sticky-left-side">

        <!--logo and iconic logo start-->
        <div class="logo">
            {% if user.is_dir or user.is_assistant %}
            <a href="{% url 'crm:main_crm' %}">
                <img src="{% static '/images/logo.png' %}" alt="">
            </a>
            {% elif user.is_superuser %}
            <a href="{% url 'admin:admin' %}">
                <img src="{% static '/images/logo.png' %}" alt="">
            </a>
            {% else %}
            <a href="{% url 'main' %}">
                <img src="{% static '/images/logo.png' %}" alt="">
            </a>
            {% endif %}
        </div>

        <div class="logo-icon text-center">
            {% if user.is_dir or user.is_assistant %}
            <a href="{% url 'crm:main_crm' %}">
                <img src="{% static '/images/logo_icon.png' %}" alt="">
            </a>
            {% elif user.is_superuser %}
            <a href="{% url 'admin:admin' %}">
                <img src="{% static '/images/logo_icon.png' %}" alt="">
            </a>
            {% else %}
            <a href="{% url 'main' %}">
                <img src="{% static '/images/logo_icon.png' %}" alt="">
            </a>
            {% endif %}
        </div>
        <!--logo and iconic logo end-->

        <div class="left-side-inner">

            <!-- visible to small devices only -->
            <div class="visible-xs hidden-sm hidden-md hidden-lg">
                <div class="media logged-user">
                    <img alt="" src="{{ user.avatar|default_avatar }}" class="media-object">
                    <div class="media-body">
                        <h4><a href="#">{{ user }}</a></h4>
                    </div>
                </div>

                <h5 class="left-nav-title">Мій аккаунт</h5>
                <ul class="nav nav-pills nav-stacked custom-nav">
                    <li>
                        <a href="{% url 'crm:worker_update' user.pk %}">
                            <i class="fa fa-user"></i> <span>Профіль</span>
                        </a>
                    </li>
                    <li><a href="#"><i class="fa fa-cog"></i> <span>Налаштування</span></a></li>
                    <li><a href="{% url 'auth:logout' %}"><i class="fa fa-sign-out"></i> <span>Вихід</span></a></li>
                </ul>
            </div>

            <!--sidebar nav start-->
            {% include 'mainapp/includes/inc_left_menu.html' %}
            <!--sidebar nav end-->
        </div>

    </div>
    <!-- left side end-->

    <!-- main content start-->
    <div class="main-content">

        <!-- header section start-->
        <div class="header-section">

            <!--toggle button start-->
            <a class="toggle-btn"><i class="fa fa-bars"></i></a>
            <!--toggle button end-->

            <!--quick button-->
            <!--{% include 'mainapp/includes/inc_quick_button.html' %}-->
            <!--quick button end-->

            <!--search start-->
            <!--<form class="searchform" action="#" method="post">-->
            <!--<input type="text" class="form-control" name="keyword" placeholder="Пошук..."/>-->
            <!--</form>-->
            <!--search end-->

            <!--notification menu start -->
            <div class="menu-right">
                {% include 'mainapp/includes/inc_right_menu.html' %}
            </div>
            <!--notification menu end -->

        </div>
        <!-- header section end-->

        <!-- page heading start -->
        <div class="page-heading">
            <h3>{{ title }}</h3>
            <!--{% block breadcrumbs %}-->
            <!--<ul class="breadcrumb">-->
            <!--<li>-->
            <!--<a href="{% url 'main' %}">Головна</a>-->
            <!--</li>-->
            <!--</ul>-->
            <!--{% endblock %}-->
        </div>
        <!-- page heading end -->

        <!--body wrapper start-->
        <div class="wrapper">
            {% block container %}
            <!-- сюда подставлям основной контент всех страниц -->
            {% endblock %}
        </div>
        <!--body wrapper end-->

    </div>
    <!-- main content end-->
</section>

{% block js %}
<script src="{% static '/js/edit_script.js' %}"></script>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="{% static '/js/html5shiv.js' %}"></script>
<script src="{% static '/js/respond.min.js' %}"></script>
<![endif]-->

<!-- Placed js at the end of the document so the pages load faster -->
<script src="{% static '/js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static '/js/jquery-ui-1.9.2.custom.min.js' %}"></script>
<script src="{% static '/js/jquery-migrate-1.2.1.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
<script src="{% static '/js/modernizr.min.js' %}"></script>
<script src="{% static '/js/jquery.nicescroll.js' %}"></script>

<!--easy pie chart-->
<script src="{% static '/js/easypiechart/jquery.easypiechart.js' %}"></script>
<script src="{% static '/js/easypiechart/easypiechart-init.js' %}"></script>

<!--Sparkline Chart-->
<script src="{% static '/js/sparkline/jquery.sparkline.js' %}"></script>
<script src="{% static '/js/sparkline/sparkline-init.js' %}"></script>

<!--icheck -->
<script src="{% static '/js/iCheck/jquery.icheck.js' %}"></script>
<script src="{% static '/js/icheck-init.js' %}"></script>

<!--pickers plugins-->
<script type="text/javascript" src="{% static '/js/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript"
        src="{% static '/js/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js' %}"></script>
<script type="text/javascript" src="{% static '/js/bootstrap-daterangepicker/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<script type="text/javascript" src="{% static '/js/bootstrap-colorpicker/js/bootstrap-colorpicker.js' %}"></script>
<script type="text/javascript" src="{% static '/js/bootstrap-timepicker/js/bootstrap-timepicker.js' %}"></script>

<!--pickers initialization-->
<script src="{% static '/js/pickers-init.js' %}"></script>

<!-- file upload -->
<script type="text/javascript" src="{% static '/js/bootstrap-fileupload.min.js' %}"></script>

<!--common scripts for all pages-->
<script src="{% static '/js/scripts.js' %}"></script>
{% endblock %}

</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} / {{ title }}
{% endblock %}

{% block container %}

<div class="row">
    {% for task in task_list %}
    <div class="col-md-3">
        <div class="panel">
            <div class="panel-body">
                {% for project in project_list %}
                {% if project.pk == task.project.pk %}
                <h4>{{ project.name }}
                    <span class="text-muted small">
                        {% if task.status == 'underway' %}
                        <span class="label label-info">Виконується</span>
                        {% elif task.status == 'done' %}
                        <span class="label label-success">Завершено</span>
                        {% else %}
                        <span class="label label-danger">Нове</span>
                        {% endif %}
                    </span>
                    <span class="small" style="float: right;"># {{ task.pk }}</span>
                </h4>
                <div class="media">
                    <a class="pull-left" href="{% url 'main:task_edit' task.pk %}">
                        {% if task.service.pk == 3 %}
                        <i class="fa fa-map-o fa-5x pull-left"></i>
                        {% elif task.service.pk == 2 %}
                        <i class="fa fa-flask fa-5x pull-left"></i>
                        {% else %}
                        <i class="fa fa-file-text-o fa-5x pull-left"></i>
                        {% endif %}
                    </a>
                    <div class="media-body">
                        <address>
                            <strong>{{ task.service }}</strong>
                            <br>
                            Створено: {{ task.date_create|date:'d.m.Y' }}
                            <br>
                            Термін: {{ task.date_end|date:'d.m.Y' }}
                            <i></i>
                        </address>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

mainapp/templates/mainapp/task_edit.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ title }} / {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-lg-6">
        <a href="{% url 'main' %}">
            <button class="btn btn-default" type="button">
                Назад
            </button>
        </a>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-8">
        <section class="panel">
            <header class="panel-heading">{{ title }}</header>
            <div class="panel-body">
                <div class="form">
                    <div class="form">
                        {% include 'crmapp/includes/inc_form_task_update.html' %}
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}