crmapp/urls.py
from django.urls import re_path
import crmapp.views as crmapp

app_name = 'crmapp'

urlpatterns = [

    re_path(r'^$', crmapp.main_crm, name='main_crm'),
    # работники
    re_path(r'^workers/list/$', crmapp.workers_list_view, name='workers_list'),
    re_path(r'^worker/detail/(?P<worker_pk>\d+)/$', crmapp.worker_detail_view, name='worker_detail'),
    re_path(r'^worker/update/(?P<worker_pk>\d+)/$', crmapp.worker_update_view, name='worker_update'),
    # контрагенты
    re_path(r'^partners/$', crmapp.partners_view, name='partners'),
    re_path(r'^partner/create/$', crmapp.partner_create_view, name='partner_create'),
    re_path(r'^partner/read/(?P<partner_pk>\d+)/$', crmapp.partner_read_view, name='partner_read'),
    re_path(r'^partner/update/(?P<partner_pk>\d+)/$', crmapp.partner_update_view, name='partner_update'),
    # фирмы
    re_path(r'^firms/$', crmapp.firms_view, name='firms'),
    re_path(r'^firm/create/$', crmapp.firm_create_view, name='firm_create'),
    re_path(r'^firm/read/(?P<firm_pk>\d+)/$', crmapp.firm_read_view, name='firm_read'),
    re_path(r'^firm/update/(?P<firm_pk>\d+)/$', crmapp.firm_update_view, name='firm_update'),
    # работы/услуги
    re_path(r'^services/$', crmapp.services_view, name='services'),
    re_path(r'^service/create/$', crmapp.service_create_view, name='service_create'),
    re_path(r'^service/update/(?P<service_pk>\d+)/$', crmapp.service_update_view, name='service_update'),
    # договора
    re_path(r'^contracts/$', crmapp.contracts_view, name='contracts'),
    re_path(r'^contract/create/$', crmapp.contract_create_view, name='contract_create'),
    re_path(r'^contract/read/(?P<contract_pk>\d+)/$', crmapp.contract_read_view, name='contract_read'),
    re_path(r'^contract/update/(?P<contract_pk>\d+)/$', crmapp.contract_update_view, name='contract_update'),
    re_path(r'^contract/edit/$', crmapp.contract_edit_view),
    # счета
    re_path(r'^invoices/$', crmapp.invoices_view, name='invoices'),
    re_path(r'^invoice/create/(?P<contract_pk>\d+)$', crmapp.invoice_create_view, name='invoice_create'),
    re_path(r'^invoice/read/(?P<invoice_pk>\d+)$', crmapp.invoice_read_view, name='invoice_read'),
    re_path(r'^invoice/update/(?P<invoice_pk>\d+)$', crmapp.invoice_update_view, name='invoice_update'),
    re_path(r'^invoice/edit/$', crmapp.invoice_edit_view),
    # акты
    re_path(r'^acts/$', crmapp.acts_view, name='acts'),
    re_path(r'^act/create/(?P<contract_pk>\d+)/$', crmapp.act_create_view, name='act_create'),
    re_path(r'^act/read/(?P<act_pk>\d+)/$', crmapp.act_read_view, name='act_read'),
    re_path(r'^act/update/(?P<act_pk>\d+)/$', crmapp.act_update_view, name='act_update'),
    # проекты
    re_path(r'^projects/$', crmapp.projects_view, name='projects'),
    re_path(r'^project/create/(?P<contract_pk>\d+)$', crmapp.project_create_view, name='project_create'),
    # re_path(r'^project/read/(?P<project_pk>\d+)$', crmapp.project_read_view, name='project_read'),
    re_path(r'^project/update/(?P<project_pk>\d+)$', crmapp.project_update_view, name='project_update'),
    # задачи
    # re_path(r'^tasks/$', crmapp.tasks_view, name='tasks'),
    re_path(r'^task/create/(?P<project_pk>\d+)$', crmapp.task_create_view, name='task_create'),
    # re_path(r'^task/read/(?P<project_pk>\d+)$', crmapp.project_read_view, name='project_read'),
    re_path(r'^task/update/(?P<task_pk>\d+)$', crmapp.task_update_view, name='task_update'),
]

vepp/urls.py
# from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, include

import mainapp.views as mainapp
# import adminapp.views as adminapp

urlpatterns = [
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^main/', include('mainapp.urls', namespace='main')),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    re_path(r'^crm/', include('crmapp.urls', namespace='crm')),
    # re_path(r'^admin/', adminapp.main_view, name='admin'),
    # re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crmapp/views.py
from datetime import datetime

from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template.loader import render_to_string
from django.http import JsonResponse

from authapp.models import ProjectUser
from authapp.forms import UserUpdateForm
from crmapp.forms import PartnerCreateForm, FirmCreateForm, ServiceCreateForm, ContractCreateForm, InvoiceCreateForm, \
    ActCreateForm, ProjectCreateForm, TaskCreateForm
from crmapp.models import Bank, Partner, Firm, Services, Contract, Invoice, Act, Project, Task


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def main_crm(request):
    title = 'Головна'
    contracts = Contract.objects.all()
    projects = Project.objects.all()
    invoices = Invoice.objects.all()
    acts = Act.objects.all()
    tasks = Task.objects.all()
    context = {
        'title': title,
        'contract_list': contracts,
        'project_list': projects,
        'invoice_list': invoices,
        'act_list': acts,
        'task_list': tasks,
    }
    return render(request, 'crmapp/index.html', context)


# просмотр списка сотрудников
@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def workers_list_view(request):
    title = 'Працівники'
    users_list = ProjectUser.objects.all().order_by('-is_active', 'username')

    context = {
        'title': title,
        'object_list': users_list,
    }
    return render(request, 'crmapp/workers_list.html', context)


# просмотр детальной информации о пользователе
@login_required
def worker_detail_view(request, worker_pk):
    title = 'Профіль працівника'
    user = get_object_or_404(ProjectUser, pk=worker_pk)
    projects = Project.objects.filter(is_finished=False)
    tasks = Task.objects.filter(worker=user).exclude(status='done').order_by('date_end')

    context = {
        'title': title,
        'object': user,
        'task_list': tasks,
        'project_list': projects,
    }
    return render(request, 'crmapp/worker_detail.html', context)


@login_required
def worker_update_view(request, worker_pk):
    title = 'Редагувати профіль'
    user = get_object_or_404(ProjectUser, pk=worker_pk)
    if user:
        if request.method == 'POST':
            form = UserUpdateForm(request.POST, request.FILES, instance=user)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('crm:workers_list'))
        else:
            form = UserUpdateForm(instance=user)

        context = {
            'title': title,
            'form': form,
            'object': user,
        }
        return render(request, 'crmapp/worker_update.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def partners_view(request):
    title = 'Контрагенти'
    partners = Partner.objects.all()

    context = {
        'title': title,
        'object_list': partners
    }

    return render(request, 'crmapp/partners_list.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def partner_create_view(request):
    title = 'Додати контрагента'
    banks = Bank.objects.all().order_by('name')
    if request.method == 'POST':
        form = PartnerCreateForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('crm:partners'))
            except Exception as e:
                pass
    else:
        form = PartnerCreateForm(initial={'banks': banks})

    context = {
        'title': title,
        'banks': banks,
        'form': form,
    }

    return render(request, 'crmapp/partner_update.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def partner_update_view(request, partner_pk):
    partner = get_object_or_404(Partner, pk=partner_pk)
    # title = f'Редагувати контрагента - {partner.short_name}'
    title = 'Редагувати контрагента - {}'.format(partner.short_name)
    if request.method == 'POST':
        form = PartnerCreateForm(request.POST, instance=partner)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('crm:partner_read', kwargs={'partner_pk': partner.pk}))
            except Exception as e:
                pass
    else:
        form = PartnerCreateForm(instance=partner)

    context = {
        'title': title,
        'form': form,
        'object': partner,
    }

    return render(request, 'crmapp/partner_update.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def partner_read_view(request, partner_pk):
    partner = get_object_or_404(Partner, pk=partner_pk)
    title = partner.short_name

    context = {
        'title': title,
        'object': partner,
    }

    return render(request, 'crmapp/partner_detail.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def firms_view(request):
    title = 'Фірми'
    firms = Firm.objects.all()

    context = {
        'title': title,
        'object_list': firms,
    }

    return render(request, 'crmapp/firms_list.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def firm_create_view(request):
    title = 'Додати фірму'
    banks = Bank.objects.all().order_by('name')
    if request.method == 'POST':
        form = FirmCreateForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('crm:firms'))
            except Exception as e:
                pass
    else:
        form = FirmCreateForm(initial={'banks': banks})

    context = {
        'title': title,
        'form': form,
        'banks': banks,
    }

    return render(request, 'crmapp/firm_update.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def firm_read_view(request, firm_pk):
    firm = get_object_or_404(Firm, pk=firm_pk)
    title = firm.short_name

    context = {
        'title': title,
        'object': firm,
    }

    return render(request, 'crmapp/firm_detail.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def firm_update_view(request, firm_pk):
    firm = get_object_or_404(Firm, pk=firm_pk)
    # title = f'Редагувати фірму - {firm.short_name}'
    title = 'Редагувати фірму - {}'.format(firm.short_name)
    if request.method == 'POST':
        form = FirmCreateForm(request.POST, instance=firm)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('crm:firm_read', kwargs={'firm_pk': firm.pk}))
            except Exception as e:
                pass
    else:
        form = FirmCreateForm(instance=firm)

    context = {
        'title': title,
        'form': form,
        'object': firm,
    }

    return render(request, 'crmapp/firm_update.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def services_view(request):
    title = 'Послуги'
    services = Services.objects.all()

    context = {
        'title': title,
        'object_list': services,
    }

    return render(request, 'crmapp/services_list.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def service_create_view(request):
    title = 'Додати роботу/послугу'
    if request.method == 'POST':
        form = ServiceCreateForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('crm:services'))
            except Exception as e:
                pass
    else:
        form = ServiceCreateForm()

    context = {
        'title': title,
        'form': form,
    }

    return render(request, 'crmapp/service_update.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def service_update_view(request, service_pk):
    title = 'Редагувати послугу/роботу'
    service = get_object_or_404(Services, pk=service_pk)
    if request.method == 'POST':
        form = ServiceCreateForm(request.POST, instance=service)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('crm:services'))
            except Exception as e:
                pass
    else:
        form = ServiceCreateForm(instance=service)

    context = {
        'title': title,
        'form': form,
        'object': service,
    }

    return render(request, 'crmapp/service_update.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def contracts_view(request):
    title = 'Договора'
    contracts = Contract.objects.all().order_by('-date_start')

    context = {
        'title': title,
        'object_list': contracts,
    }

    return render(request, 'crmapp/contracts_list.html', context)


@login_required
@user_passes_test(lambda user: user.is_assistant or user.is_superuser or user.is_dir)
def contract_create_view(request):
    title = 'Додати договір'
    client = Partner.objects.all().order_by('short_name')
    performer = Firm.objects.all().order_by('short_name')
    if request.method == 'POST':
        form = ContractCreateForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('crm:contracts'))

crmapp/templates/crmapp/act_update.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ title }} / {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-lg-8">
        <section class="panel">
            <header class="panel-heading">{{ title }}</header>
            <div class="panel-body">
                <div class="form">
                    <div class="form">
                        {% include 'crmapp/includes/inc_form_act_update.html' %}
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}

crmapp/templates/crmapp/contract_detail.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
    {{ title }} / {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-lg-6">
        <a href="{% url 'crm:contract_update' object.pk %}">
            <button class="btn btn-primary" type="button">Редагувати</button>
        </a>
        <a href="{% url 'crm:invoice_create' object.pk %}">
            <button class="btn btn-primary" type="button">Рахунок <i class="fa fa-plus"></i></button>
        </a>
        <a href="{% url 'crm:act_create' object.pk %}">
            <button class="btn btn-primary" type="button">Акт <i class="fa fa-plus"></i></button>
        </a>
        <a href="{% url 'crm:project_create' object.pk %}">
            <button class="btn btn-primary" type="button">Проект <i class="fa fa-plus"></i></button>
        </a>
        <a href="{% url 'crm:contracts' %}">
            <button class="btn btn-default" type="button">Назад</button>
        </a>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                Основна інформація
            </header>
            <div class="panel-body">
                <ul class="p-info">
                    <li>
                        <div class="title">№ договору</div>
                        <div class="desk">{{ object.number }}</div>
                    </li>
                    <li>
                        <div class="title">Дата укладання</div>
                        <div class="desk">{{ object.date_start }}</div>
                    </li>
                    <li>
                        <div class="title">Термін виконання</div>
                        <div class="desk">{{ object.date_end }}</div>
                    </li>
                    <li>
                        <div class="title">Замовник</div>
                        <div class="desk">{{ object.client }}</div>
                    </li>
                    <li>
                        <div class="title">Виконавець</div>
                        <div class="desk">{{ object.performer }}</div>
                    </li>
                    <li>
                        <div class="title">Предмет договору</div>
                        <div class="desk">{{ object.works }}</div>
                    </li>
                    <li>
                        <div class="title">Вартість</div>
                        <div class="desk">{{ object.cost }}&nbsp;грн.</div>
                    </li>
                    <li>
                        <div class="title">Термін виконання</div>
                        <div class="desk">{{ object.date_end }}</div>
                    </li>
                    <li>
                        <div class="title">Район</div>
                        <div class="desk">{{ object.district }}</div>
                    </li>
                    <li>
                        <div class="title">Населений пункт</div>
                        <div class="desk">{{ object.town }}</div>
                    </li>
                    <li>
                        <div class="title">Адреса</div>
                        <div class="desk">{{ object.address }}</div>
                    </li>
                    <li>
                        <div class="title">Примітка</div>
                        <div class="desk">{{ object.note }}</div>
                    </li>
                </ul>
            </div>
        </section>
    </div>
        <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                Проект
            </header>
            <div class="panel-body" style="display: block;">
                <table class="table table-hover general-table">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>Дата початку</th>
                        <th>Дата закінчення</th>
                        <th>Прогрес</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for project in project_list %}
                    <tr>
                        <td>
                            <a style="display: block; text-decoration: none;"
                               href="{% url 'crm:projects' %}">
                                {{ project.pk }}
                            </a>
                        </td>
                        <td>{{ project.date_create|date:"d.m.Y" }} р.</td>
                        <td>{{ project.date_end|date:"d.m.Y" }} р.</td>
                        <td>
                            <div class="progress">
                                <div class="progress-bar progress-bar-success" role="progressbar"
                                     aria-valuenow="{{ object.status }}" aria-valuemin="0"
                                     aria-valuemax="100" style="width: {{ project.status }}%;">
                                    <!--<span class="sr-only">60% Complete</span>-->
                                    {{ project.status }}%
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </div>
     <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                Рахунки
            </header>
                <div class="panel-body" style="display: block;">
                    <table class="table table-hover general-table">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Дата</th>
                            <th>Сума, грн.</th>
                            <th>Оплачено</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for invoice in invoice_list %}
                        <tr>
                            <td>
                                <a style="display: block; text-decoration: none;"
                                   href="{% url 'crm:invoice_read' invoice.pk %}">
                                    {{ invoice.num_invoice }}
                                </a>
                            </td>
                            <td>{{ invoice.date_create|date:"d.m.Y" }} р.</td>
                            <td>{{ invoice.price }}</td>
                            <td>
                                {% if invoice.is_paid %}
                                <i class="fa fa-check fa-lg" aria-hidden="true" title="Так"></i>
                                {% else %}
                                <i class="fa fa-times fa-lg" aria-hidden="true" title="Ні"></i>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
        </section>
    </div>
    <div class="col-lg-6">
        <section class="panel">
            <header class="panel-heading">
                Акти
            </header>
            <div class="panel-body" style="display: block;">
                <table class="table table-hover general-table">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>Дата</th>
                        <th>Сума, грн.</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for act in act_list %}
                    <tr>
                        <td>
                            <a style="display: block; text-decoration: none;"
                               href="{% url 'crm:act_read' act.pk %}">
                                {{ act.num_act }}
                            </a>
                        </td>
                        <td>{{ act.date_create|date:"d.m.Y" }} р.</td>
                        <td>{{ act.price }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
{% endblock %}

crmapp/templates/crmapp/projects_list2.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
{{ title }} / {{ block.super }}
{% endblock %}

{% block container %}
<div class="directory-info-row">
    <div class="row">
        <div class="col-lg-6">
            <!--<a href="{% url 'crm:contract_create' %}">-->
            <!--<button class="btn btn-primary" type="button"><i class="fa fa-plus"></i> Додати</button>-->
            <!--</a>-->
            <a href="{% url 'crm:main_crm' %}">
                <button class="btn btn-default" type="button">Назад</button>
            </a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">
            {% for object in object_list %}
            {% if not object.is_finished %}
            <section class="panel">
                <header class="panel-heading">
                    {{ object.name }}
                    <span class="tools pull-right">
            <a class="fa fa-chevron-up" href="javascript:;"></a>
            </span>
                </header>
                <div class="panel-body" style="display: none;">
                    <div class="col-lg-3">
                        <ul class="p-info">
                            <li>
                                <div class="title">№ проекту</div>
                                <div class="desk">{{ object.pk }}</div>
                            </li>
                            <li>
                                <div class="title">№ договору</div>
                                <div class="desk">{{ object.contract.number }}</div>
                            </li>
                            <li>
                                <div class="title">Дата створення</div>
                                <div class="desk">{{ object.date_create }}</div>
                            </li>
                            <li>
                                <div class="title">Змінено</div>
                                <div class="desk">{{ object.date_change }}</div>
                            </li>
                            <li>
                                <div class="title">Дата завершення</div>
                                <div class="desk">{{ object.date_end }}</div>
                            </li>
                            <li>
                                <div class="title">Виконано</div>
                                <div class="desk">
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-success" role="progressbar"
                                             aria-valuenow="{{ object.status }}" aria-valuemin="0"
                                             aria-valuemax="100" style="width: {{ object.status }}%;">
                                            <!--<span class="sr-only">60% Complete</span>-->
                                            {{ object.status }}%
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-1">
                        <ul class="p-info">
                            <li>
                                <a href="{% url 'crm:project_update' object.pk %}">
                                    <button class="btn btn-default" type="button" title="Редагувати проект">
                                        <i class="fa fa-pencil"></i>
                                    </button>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'crm:task_create' object.pk %}">
                                    <button class="btn btn-default" type="button" title="Нове завдання">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-8">
                        <div class="panel-body" style="display: block;">
                            <table class="table table-hover general-table">
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Виконавець</th>
                                    <th>Робота</th>
                                    <th>Дата початку</th>
                                    <th>Строк</th>
                                    <th>Статус</th>
                                    <th>&nbsp;</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for task in task_list %}
                                {% if object.pk == task.project.pk %}
                                <tr>
                                    <td>{{ task.pk }}</td>
                                    <td>{{ task.worker }}</td>
                                    <td>{{ task.service }}</td>
                                    <td>{{ task.date_create|date:"d.m.Y" }} р.</td>
                                    <td>{{ task.date_end|date:"d.m.Y" }} р.</td>
                                    {% if not task.status %}
                                    <td><span class="label label-danger label-mini">Нове</span></td>
                                    {% elif task.status == 'underway' %}
                                    <td><span class="label label-primary label-mini">Виконується</span></td>
                                    {% elif task.status == 'done' %}
                                    <td><span class="label label-success label-mini">Завершено</span></td>
                                    {% endif %}
                                    <td>
                                        <a href="{% url 'crm:task_update' task.pk %}">
                                            <button class="btn btn-default btn-xs" type="button"
                                                    title="Редагувати завдання">
                                                <i class="fa fa-pencil"></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

crmapp/templates/crmapp/task_update.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ title }} / {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-lg-6">
        <a href="{% url 'crm:projects' %}">
            <button class="btn btn-default" type="button">
                Назад
            </button>
        </a>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-8">
        <section class="panel">
            <header class="panel-heading">{{ title }}</header>
            <div class="panel-body">
                <div class="form">
                    <div class="form">
                        {% include 'crmapp/includes/inc_form_task_update.html' %}
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}